# 🐼 **Pandas EDA & Data Cleaning Tutorial**

### This notebook demonstrates a variety of essential and practical Pandas techniques for exploratory data analysis (EDA) and preprocessing. You'll find examples of:
- Series and DataFrames
- Loading and inspecting datasets
- Handling missing values and duplicates
- Text cleaning and string operations
- Merging and joining datasets
- Working with datetime features
- Filtering, sorting, and saving data

---

## 📘 **What is a DataFrame?**
A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types, similar to a spreadsheet or SQL table.

### ---------------------------------------------------------------------------------------------------------------------------------

## 1. Pandas Series

In [34]:
import pandas as pd

In [38]:
groceries= pd.Series(data=[30,6,'Yes','No'],index=['eggs','apples','milk','bread'])
print(groceries)
print('--------'*3)
print('banana' in groceries)
print('--------'*3)
print( groceries.values)
print('--------'*3)
print('bread' in groceries)
print('--------'*3)
print(groceries.drop('apples'))
print('--------'*3)
print(groceries['eggs'])
print('--------'*3)
print(groceries[['milk','bread']])

eggs       30
apples      6
milk      Yes
bread      No
dtype: object
------------------------
False
------------------------
[30 6 'Yes' 'No']
------------------------
True
------------------------
eggs      30
milk     Yes
bread     No
dtype: object
------------------------
30
------------------------
milk     Yes
bread     No
dtype: object

In [57]:
fruits=pd.Series([10,6,3],['apples','oranges','bananas'])    # by default  ( data= ,   index=  )
fruits *2    #  -2,   *2,  /2

apples     20
oranges    12
bananas     6
dtype: int64

In [40]:
top_name=['high','medium','low']
score=[10,25,40]
total=pd.Series(data=score,index=top_name)

print(total)
print(type(total))

high      10
medium    25
low       40
dtype: int64
<class 'pandas.core.series.Series'>

### ---------------------------------------------------------------------------------------------------------------------------------

## 2. Pandas Dataframe

In [42]:
df1= pd.DataFrame(10,index=['X','Y','Z'],columns=['C1','C2'])
print(df1)

   C1  C2
X  10  10
Y  10  10
Z  10  10

In [46]:
# new_var=df1.drop('C1',axis=1)    # delete  vertical    ,   0: delete horizotnal
df1.drop('C1',axis=1,inplace=True)   # make effect on column
# df1.drop('Y',axis=0,inplace=True)
df1

   C2
X  10
Y  10
Z  10

In [14]:
ice_cream_data=[['chocolate',23],['vanilla',45],['cream',13]]
ice_cream=pd.DataFrame(data=ice_cream_data,index=['Flavor 1','Flavor 2', 'Flavor 3'],columns=['Flavor','Price'])
print(ice_cream)
print(type(ice_cream))

             Flavor  Price
Flavor 1  chocolate     23
Flavor 2    vanilla     45
Flavor 3      cream     13
<class 'pandas.core.frame.DataFrame'>

## ---------------------------------------------------------------------------------------------------

## 🔍 Inspecting DataFrames

# 1. Loading Datasets

In [127]:
# Set maximum columns and rows to be displayed in dataframe as 40 columns and 200 rows
pd.set_option('display.max.rows', 200)
pd.set_option('display.max.columns', 40)

In [129]:
# df=pd.read_csv(r'C:\Users\Maged\Desktop\Pandas\Pandas_Exercise\countries of the world.csv')
# df=pd.read_csv(r'C:\Users\Maged\Desktop\Pandas\Pandas_Exercise\countries of the world.txt',sep='\t')
# df = pd.read_table(r"C:\Users\Maged\Desktop\Pandas\Pandas_Exercise\countries of the world.csv", sep = ',')
# df = pd.read_json(r"C:\Users\Maged\Desktop\Pandas\Pandas_Exercise\json_sample.json")
# df= pd.read_excel(r"C:\Users\Maged\Desktop\Pandas\Pandas_Exercise\world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df=pd.read_csv(r'C:\Users\Maged\Desktop\PANDAS\DataSets\Customer Call List.csv')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

# 2. Exploring the Dataset

In [131]:
df.shape            # SIZE of my data, Rows and columns

(21, 10)

In [133]:
 df.info()           # Data types and non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
 8   Unnamed: 8         0 non-null      float64
 9   Unnamed: 9         0 non-null      float64
dtypes: bool(1), float64(2), int64(1), object(6)
memory usage: 1.6+ KB

In [135]:
df.describe()       # Some analysis on columns with numbers

        CustomerID  Unnamed: 8  Unnamed: 9
count    21.000000         0.0         0.0
mean   1010.952381         NaN         NaN
std       6.127611         NaN         NaN
min    1001.000000         NaN         NaN
25%    1006.000000         NaN         NaN
50%    1011.000000         NaN         NaN
75%    1016.000000         NaN         NaN
max    1020.000000         NaN         NaN

In [137]:
df.columns          # List of column names

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column', 'Unnamed: 8',
       'Unnamed: 9'],
      dtype='object')

In [139]:
df.head()           # First few rows

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN

In [141]:
df.tail()           # Last few rows

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

# 3.Check for Missing Values

In [143]:
df.isnull().sum()                  # Missing values per column
# df.isnull().mean() * 100          # Missing percentage

CustomerID            0
First_Name            0
Last_Name             1
Phone_Number          2
Address               0
Paying Customer       0
Do_Not_Contact        4
Not_Useful_Column     0
Unnamed: 8           21
Unnamed: 9           21
dtype: int64

# 4. Data Cleaning
## 🧼 Handling Missing Values

In [145]:
df=df.drop(columns="Unnamed: 8")
# df = df.replace('N/a','')
# df = df.replace('NaN','')

In [147]:
# df.dropna(inplace=True)                       # Drop rows with missing values

In [149]:
df.fillna("Not Available",inplace=True)

C:\Users\Maged\AppData\Local\Temp\ipykernel_17188\2483682220.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("Not Available",inplace=True)

## 🧹 Removing Duplicates

In [151]:
df.duplicated().sum()     # duplicated  return a boolean value for each raw

1

In [153]:
df.drop_duplicates(inplace=True)

## 📝 String Cleaning

In [159]:
df["Last_Name"] = df["Last_Name"].str.strip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Not Available
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Not Available
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,Not Available,True,Not Available
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Not Available
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Not Available
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Not Available
6,1007,Jeff,Winger,Not Available,1209 South Street,No,No,False,Not Available
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Not Available
8,1009,Gandalf,Not Available,N/a,123 Middle Earth,Yes,Not Available,False,Not Available
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Not Available
10,1011,Samwise,Gamgee,Not Available,"612 Shire Lane, Shire",Yes,No,True,Not Available
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,Not Available,True,Not Available
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Not Available
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,Not Available
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,Not Available
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Not Available
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,Not Available
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,Not Available,True,Not Available
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Not Available
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Not Available

## 🧩 Merging & Joining

In [163]:
# df1.merge(df2, how = 'inner', on = ['column_1', 'column_2'])
# df1.merge(df2, how = 'outer')
# df1.merge(df2, how = 'left')
# df1.merge(df2, how = 'right')
# df1.merge(df2, how = 'cross')
# pd.concat([df1,df2], join = 'outer', axis = 1)
# df1.append(df2)

## ⏰ Datetime Features

In [165]:
# df['date_column'] = pd.to_datetime(df['date_column'])
# df['year'] = df['date_column'].dt.year
# df['month'] = df['date_column'].dt.month
# df['day'] = df['date_column'].dt.day

## 🔎 Filtering & Sorting

In [186]:
df[(df['Paying Customer']=='No') & (df['Do_Not_Contact']=='Yes')]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 9
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Not Available

In [176]:
print(df.loc[0])       # to get data on only row 1

CustomerID                            1001
First_Name                           Frodo
Last_Name                          Baggins
Phone_Number                  123-545-5421
Address              123 Shire Lane, Shire
Paying Customer                        Yes
Do_Not_Contact                          No
Not_Useful_Column                     True
Unnamed: 9                   Not Available
Name: 0, dtype: object

In [174]:
print(df.loc[[0,1]])    # to get data of only row 1 & 2

   CustomerID First_Name Last_Name  Phone_Number                Address  \
0        1001      Frodo   Baggins  123-545-5421  123 Shire Lane, Shire
1        1002       Abed     Nadir  123/643/9775    93 West Main Street

  Paying Customer Do_Not_Contact  Not_Useful_Column     Unnamed: 9
0             Yes             No               True  Not Available
1              No            Yes              False  Not Available

In [170]:
df[df['First_Name'].str.contains('Peter')]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 9
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Not Available

In [168]:
df[df['CustomerID'] <= 1010]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Not Available
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Not Available
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,Not Available,True,Not Available
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Not Available
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Not Available
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Not Available
6,1007,Jeff,Winger,Not Available,1209 South Street,No,No,False,Not Available
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Not Available
8,1009,Gandalf,Not Available,N/a,123 Middle Earth,Yes,Not Available,False,Not Available
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Not Available

In [198]:
df.Address       # calling out a column

0                     123 Shire Lane, Shire
1                       93 West Main Street
2                        298 Drugs Driveway
3     980 Paper Avenue, Pennsylvania, 18503
4                          123 Dragons Road
5                          768 City Parkway
6                         1209 South Street
7                             98 Clue Drive
8                          123 Middle Earth
9                25th Main Street, New York
10                    612 Shire Lane, Shire
11                     2394 Hogwarts Avenue
12                         2039 Main Street
13                         343 City Parkway
14                            214 HR Avenue
15                     2395 Hogwarts Avenue
16           121 Paper Avenue, Pennsylvania
17                          3498 Super Lane
18                                      N/a
19              910 Tatooine Road, Tatooine
Name: Address, dtype: object

In [ ]:
df['Paying Customer']       # calling out a column with SPACES

In [194]:
df[['First_Name','Last_Name','Address']]      # calling out multiple columns

   First_Name      Last_Name                                Address
0       Frodo        Baggins                  123 Shire Lane, Shire
1        Abed          Nadir                    93 West Main Street
2      Walter          White                     298 Drugs Driveway
3      Dwight        Schrute  980 Paper Avenue, Pennsylvania, 18503
4         Jon           Snow                       123 Dragons Road
5         Ron        Swanson                       768 City Parkway
6        Jeff         Winger                      1209 South Street
7    Sherlock         Holmes                          98 Clue Drive
8     Gandalf  Not Available                       123 Middle Earth
9       Peter         Parker             25th Main Street, New York
10    Samwise         Gamgee                  612 Shire Lane, Shire
11      Harry         Potter                   2394 Hogwarts Avenue
12        Don         Draper                       2039 Main Street
13     Leslie          Knope                       343 City Parkway
14       Toby     Flenderson                          214 HR Avenue
15        Ron        Weasley                   2395 Hogwarts Avenue
16   Michael           Scott         121 Paper Avenue, Pennsylvania
17      Clark           Kent                        3498 Super Lane
18      Creed         Braton                                    N/a
19     Anakin      Skywalker            910 Tatooine Road, Tatooine

In [190]:
df.Address.unique()

array(['123 Shire Lane, Shire', '93 West Main Street',
       '298 Drugs Driveway', '980 Paper Avenue, Pennsylvania, 18503',
       '123 Dragons Road', '768 City Parkway', '1209 South Street',
       '98 Clue Drive', '123 Middle Earth', '25th Main Street, New York',
       '612 Shire Lane, Shire', '2394 Hogwarts Avenue',
       '2039 Main Street', '343 City Parkway', '214 HR Avenue',
       '2395 Hogwarts Avenue', '121 Paper Avenue, Pennsylvania',
       '3498 Super Lane', 'N/a', '910 Tatooine Road, Tatooine'],
      dtype=object)

## 💾 10. Saving the Cleaned Dataset

In [ ]:
# Save the cleaned DataFrame to a new CSV file
df.to_csv("cleaned_dataset.csv", index=False)      #index: Keeps only actual data columns in the output file.

# Optional: Save to Excel
# df.to_excel("cleaned_dataset.xlsx", index=False)

# *************************************************************************